/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: .sanity/schema.json
export type LinkInBio = {
  _id: string
  _type: "linkInBio"
  _createdAt: string
  _updatedAt: string
  _rev: string
  heading: string
  bio?: string
  links?: Array<{
    link: SourceLink
    emoji?: string
    highlight?: boolean
    _key: string
  }>
}

export type HomePageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "homePage"
}

export type EventsPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "eventsPage"
}

export type RoomsPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "roomsPage"
}

export type GroupsPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "groupsPage"
}

export type SponsorsPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sponsorsPage"
}

export type KontaktPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "kontaktPage"
}

export type PageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "page"
}

export type ArrangementReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "arrangement"
}

export type RoomReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "room"
}

export type StudentGroupReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "studentGroup"
}

export type SourceLink = {
  _type: "sourceLink"
  label: string
  linkType: "internalPage" | "internalPath" | "external"
  internalPage?:
    | HomePageReference
    | EventsPageReference
    | RoomsPageReference
    | GroupsPageReference
    | SponsorsPageReference
    | KontaktPageReference
    | PageReference
    | ArrangementReference
    | RoomReference
    | StudentGroupReference
  internalPath?: string
  externalUrl?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type SiteMetadata = {
  _id: string
  _type: "siteMetadata"
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteName?: string
  openingHours?: OpeningHours
  houseClosedDates?: Array<{
    date: string
    note?: string
    _type: "houseClosedDate"
    _key: string
  }>
  defaultSeoTitle?: string
  defaultSeoDescription?: string
  defaultOpenGraphImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  defaultOpenGraphTitle?: string
  defaultOpenGraphDescription?: string
  oembedTitle?: string
  oembedDescription?: string
  oembedImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x: number
  y: number
  height: number
  width: number
}

export type OpeningHours = {
  _type: "openingHours"
  rows?: Array<
    {
      _key: string
    } & OpeningHoursRow
  >
}

export type Footer = {
  _id: string
  _type: "footer"
  _createdAt: string
  _updatedAt: string
  _rev: string
  socialLinks?: Array<
    {
      _key: string
    } & FooterSocialLink
  >
}

export type Navbar = {
  _id: string
  _type: "navbar"
  _createdAt: string
  _updatedAt: string
  _rev: string
  items: Array<
    {
      _key: string
    } & NavItem
  >
}

export type ArrangementDate = {
  _type: "arrangementDate"
  startDate: string
  startTime?: string
  endTime?: string
}

export type FooterSocialLink = {
  _type: "footerSocialLink"
  platform:
    | "instagram"
    | "facebook"
    | "youtube"
    | "tiktok"
    | "snapchat"
    | "flickr"
    | "other"
  label: string
  url: string
}

export type InternbevisBenefit = {
  _id: string
  _type: "internbevisBenefit"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  description: string
  minimumTier: "trinn1" | "trinn2" | "trinn3"
}

export type ContactGroup = {
  _type: "contactGroup"
  title: string
  persons?: Array<
    {
      _key: string
    } & ContactPerson
  >
}

export type ContactPerson = {
  _type: "contactPerson"
  name: string
  rolle?: string
  email?: string
  phone?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
}

export type Menu = {
  _type: "menu"
  sections?: Array<
    {
      _key: string
    } & MenuSection
  >
  allergenNote?: string
}

export type MenuSection = {
  _type: "menuSection"
  title: string
  fixedPrice?: number
  info?: string
  items?: Array<
    {
      _key: string
    } & MenuItem
  >
}

export type MenuItem = {
  _type: "menuItem"
  title: string
  description?: string
  price?: number
}

export type NavItem = {
  _type: "navItem"
  label: string
  href?: string
  externalUrl?: string
  children?: Array<{
    groupLabel?: string
    items: Array<{
      label: string
      href?: string
      externalUrl?: string
      _type: "navLeaf"
      _key: string
    }>
    _type: "navGroup"
    _key: string
  }>
}

export type PortableTextContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        target?: "self" | "blank"
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      caption?: string
      _type: "image"
      _key: string
    }
>

export type OpeningHoursRow = {
  _type: "openingHoursRow"
  weekdays?: Array<number>
  status?: "open" | "closed"
  duration?: Duration
  note?: string
}

export type Duration = {
  _type: "duration"
  start: TimeValue
  end: TimeValue
}

export type TimeValue =
  | "00:00"
  | "00:30"
  | "01:00"
  | "01:30"
  | "02:00"
  | "02:30"
  | "03:00"
  | "03:30"
  | "04:00"
  | "04:30"
  | "05:00"
  | "05:30"
  | "06:00"
  | "06:30"
  | "07:00"
  | "07:30"
  | "08:00"
  | "08:30"
  | "09:00"
  | "09:30"
  | "10:00"
  | "10:30"
  | "11:00"
  | "11:30"
  | "12:00"
  | "12:30"
  | "13:00"
  | "13:30"
  | "14:00"
  | "14:30"
  | "15:00"
  | "15:30"
  | "16:00"
  | "16:30"
  | "17:00"
  | "17:30"
  | "18:00"
  | "18:30"
  | "19:00"
  | "19:30"
  | "20:00"
  | "20:30"
  | "21:00"
  | "21:30"
  | "22:00"
  | "22:30"
  | "23:00"
  | "23:30"

export type EditorialSection = {
  _type: "editorialSection"
  title?: string
  paragraphs: Array<string>
  links?: Array<
    {
      _key: string
    } & SourceLink
  >
}

export type SourcedImage = {
  _type: "sourcedImage"
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  alt?: string
  caption?: string
}

export type EventTypeReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "eventType"
}

export type Arrangement = {
  _id: string
  _type: "arrangement"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  eventType?: EventTypeReference
  isInternalEvent?: boolean
  description?: PortableTextContent
  dates: Array<
    {
      _key: string
    } & ArrangementDate
  >
  isRecurring?: boolean
  rrule?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  imageCaption?: string
  room?: RoomReference
  roomText?: string
  organizerGroup?: StudentGroupReference
  organizerText?: string
  isFree?: boolean
  priceOrdinar?: number
  priceStudent?: number
  priceMedlem?: number
  ticketUrl?: string
  facebookUrl?: string
  seoTitle?: string
  seoDescription?: string
  openGraphImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  openGraphTitle?: string
  openGraphDescription?: string
  oembedTitle?: string
  oembedDescription?: string
  oembedImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  approvalStatus?: "pending" | "approved" | "rejected" | "archived"
  submittedBy?: string
  submittedByEmail?: string
  submittedByOrganization?: string
  adminNote?: string
}

export type StudentGroup = {
  _id: string
  _type: "studentGroup"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  category: "arbeidsgruppe" | "komitee" | "dorg" | "borg"
  parentGroup?: StudentGroupReference
  summary: string
  body?: PortableTextContent
  recruitmentLabel?: string
  recruitmentLead?: string
  recruitmentSections?: Array<{
    title: string
    paragraphs: Array<string>
    _type: "recruitmentSection"
    _key: string
  }>
  email?: string
  website?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  labels?: Array<string>
  image?: SourcedImage
  orderRank?: string
}

export type Slug = {
  _type: "slug"
  current: string
  source?: string
}

export type Room = {
  _id: string
  _type: "room"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  summary: string
  body?: PortableTextContent
  crescatRoomId?: number
  menu?: Menu
  orderRank?: string
  floor?: number
  capacityStanding?: number
  capacitySeated?: number
  suitedPurposes?: Array<string>
  bar?: string
  hasSound?: boolean
  soundDetails?: string
  hasLighting?: boolean
  lightingDetails?: string
  hasAV?: boolean
  avDetails?: string
  specsUrl?: string
  openingHours?: OpeningHours
  panoramaUrl?: string
  images?: Array<
    {
      _key: string
    } & SourcedImage
  >
}

export type EventTaxonomyGroupReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "eventTaxonomyGroup"
}

export type EventType = {
  _id: string
  _type: "eventType"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  taxonomyGroup: EventTaxonomyGroupReference
  description?: string
  isActive?: boolean
  orderRank?: string
}

export type EventTaxonomyGroup = {
  _id: string
  _type: "eventTaxonomyGroup"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  isActive?: boolean
  orderRank?: string
}

export type Page = {
  _id: string
  _type: "page"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: Markdown
  seoTitle?: string
  seoDescription?: string
}

export type Markdown = string

export type KontaktPage = {
  _id: string
  _type: "kontaktPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  visitAddress?: string
  postAddress?: string
  invoiceAddress?: string
  invoiceEmail?: string
  ehf?: string
  generalContact?: string
  pressContact?: string
  contactGroups?: Array<
    {
      _key: string
    } & ContactGroup
  >
  seoTitle?: string
  seoDescription?: string
}

export type SponsorsPage = {
  _id: string
  _type: "sponsorsPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  title: string
  description?: string
  sponsors?: Array<{
    logo?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    title: string
    description?: PortableTextContent
    website?: string
    _type: "sponsor"
    _key: string
  }>
  seoTitle?: string
  seoDescription?: string
}

export type GroupsPage = {
  _id: string
  _type: "groupsPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  title: string
  description?: string
  sections?: Array<
    {
      _key: string
    } & EditorialSection
  >
  seoTitle?: string
  seoDescription?: string
  faq?: Array<{
    question: string
    answer: Array<string>
    _type: "faqItem"
    _key: string
  }>
}

export type SanityFileAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset"
}

export type RoomsPage = {
  _id: string
  _type: "roomsPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  title: string
  description?: string
  sections?: Array<
    {
      _key: string
    } & EditorialSection
  >
  bookingLink?: SourceLink
  floorPlans?: Array<{
    floor: number
    title?: string
    file: {
      asset?: SanityFileAssetReference
      media?: unknown
      _type: "file"
    }
    _type: "floorPlan"
    _key: string
  }>
  seoTitle?: string
  seoDescription?: string
}

export type EventsPage = {
  _id: string
  _type: "eventsPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  title?: string
  description?: string
  seoTitle?: string
  seoDescription?: string
  openGraphImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  openGraphTitle?: string
  openGraphDescription?: string
  oembedTitle?: string
  oembedDescription?: string
  oembedImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
}

export type HomePage = {
  _id: string
  _type: "homePage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  title: string
  description?: string
  primaryCta?: SourceLink
  seoTitle?: string
  seoDescription?: string
  openGraphImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  openGraphTitle?: string
  openGraphDescription?: string
  oembedTitle?: string
  oembedDescription?: string
  oembedImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
}

export type RecurringDates = {
  _type: "recurringDates"
  startDate: string
  endDate?: string
  recurs?: boolean
  rrule?: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | LinkInBio
  | HomePageReference
  | EventsPageReference
  | RoomsPageReference
  | GroupsPageReference
  | SponsorsPageReference
  | KontaktPageReference
  | PageReference
  | ArrangementReference
  | RoomReference
  | StudentGroupReference
  | SourceLink
  | SanityImageAssetReference
  | SiteMetadata
  | SanityImageCrop
  | SanityImageHotspot
  | OpeningHours
  | Footer
  | Navbar
  | ArrangementDate
  | FooterSocialLink
  | InternbevisBenefit
  | ContactGroup
  | ContactPerson
  | Menu
  | MenuSection
  | MenuItem
  | NavItem
  | PortableTextContent
  | OpeningHoursRow
  | Duration
  | TimeValue
  | EditorialSection
  | SourcedImage
  | EventTypeReference
  | Arrangement
  | StudentGroup
  | Slug
  | Room
  | EventTaxonomyGroupReference
  | EventType
  | EventTaxonomyGroup
  | Page
  | Markdown
  | KontaktPage
  | SponsorsPage
  | GroupsPage
  | SanityFileAssetReference
  | RoomsPage
  | EventsPage
  | HomePage
  | RecurringDates
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
