/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: .sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HomeBar = {
  _id: string;
  _type: "homeBar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nameNb?: string;
  nameEn?: string;
  descriptionNb?: string;
  descriptionEn?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type EventsPage = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrowNb?: string;
  eyebrowEn?: string;
  titleNb?: string;
  titleEn?: string;
  descriptionNb?: string;
  descriptionEn?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  badgeNb?: string;
  badgeEn?: string;
  heroDescriptionNb?: string;
  heroDescriptionEn?: string;
  heroDescriptionFusionNb?: string;
  heroDescriptionFusionEn?: string;
  eventsLinkNb?: string;
  eventsLinkEn?: string;
};

export type SiteMetadata = {
  _id: string;
  _type: "siteMetadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitleNb?: string;
  siteTitleEn?: string;
  siteDescriptionNb?: string;
  siteDescriptionEn?: string;
  homeTitleNb?: string;
  homeTitleEn?: string;
  homeDescriptionNb?: string;
  homeDescriptionEn?: string;
  eventsTitleNb?: string;
  eventsTitleEn?: string;
  eventsDescriptionNb?: string;
  eventsDescriptionEn?: string;
  volunteerSignupTitleNb?: string;
  volunteerSignupTitleEn?: string;
  volunteerSignupDescriptionNb?: string;
  volunteerSignupDescriptionEn?: string;
  groupPageTitleNb?: string;
  groupPageTitleEn?: string;
  groupPageDescriptionNb?: string;
  groupPageDescriptionEn?: string;
};

export type VolunteerGroupSummary = {
  _id: string;
  _type: "volunteerGroupSummary";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  descriptionNb?: string;
  descriptionEn?: string;
  order?: number;
};

export type LaunchGroup = {
  _id: string;
  _type: "launchGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: string;
  nameNb?: string;
  nameEn?: string;
  eyebrowNb?: string;
  eyebrowEn?: string;
  leadNb?: string;
  leadEn?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  accordionSections?: Array<
    {
      _key: string;
    } & GroupSection
  >;
  detailSections?: Array<
    {
      _key: string;
    } & GroupSection
  >;
};

export type GroupSection = {
  _type: "groupSection";
  titleNb?: string;
  titleEn?: string;
  paragraphsNb?: Array<string>;
  paragraphsEn?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | HomeBar
  | SanityImageCrop
  | SanityImageHotspot
  | EventsPage
  | HomePage
  | SiteMetadata
  | VolunteerGroupSummary
  | LaunchGroup
  | GroupSection
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: lib/sanity/query-definitions.ts
// Variable: launchGroupsNbQuery
// Query: *[_type == "launchGroup"] | order(_createdAt asc) {    slug,    "name": nameNb,    "eyebrow": eyebrowNb,    "lead": leadNb,    "imageUrl": image.asset->url,    "accordionSections": accordionSections[] {        "title": titleNb,        "paragraphs": paragraphsNb    },    "detailSections": detailSections[] {        "title": titleNb,        "paragraphs": paragraphsNb    }}
export type LaunchGroupsNbQueryResult = Array<{
  slug: string | null;
  name: string | null;
  eyebrow: string | null;
  lead: string | null;
  imageUrl: string | null;
  accordionSections: Array<{
    title: string | null;
    paragraphs: Array<string> | null;
  }> | null;
  detailSections: Array<{
    title: string | null;
    paragraphs: Array<string> | null;
  }> | null;
}>;

// Source: lib/sanity/query-definitions.ts
// Variable: launchGroupsEnQuery
// Query: *[_type == "launchGroup"] | order(_createdAt asc) {    slug,    "name": nameEn,    "eyebrow": eyebrowEn,    "lead": leadEn,    "imageUrl": image.asset->url,    "accordionSections": accordionSections[] {        "title": titleEn,        "paragraphs": paragraphsEn    },    "detailSections": detailSections[] {        "title": titleEn,        "paragraphs": paragraphsEn    }}
export type LaunchGroupsEnQueryResult = Array<{
  slug: string | null;
  name: string | null;
  eyebrow: string | null;
  lead: string | null;
  imageUrl: string | null;
  accordionSections: Array<{
    title: string | null;
    paragraphs: Array<string> | null;
  }> | null;
  detailSections: Array<{
    title: string | null;
    paragraphs: Array<string> | null;
  }> | null;
}>;

// Source: lib/sanity/query-definitions.ts
// Variable: volunteerGroupSummariesNbQuery
// Query: *[_type == "volunteerGroupSummary"] | order(order asc) {    name,    "description": descriptionNb}
export type VolunteerGroupSummariesNbQueryResult = Array<{
  name: string | null;
  description: string | null;
}>;

// Source: lib/sanity/query-definitions.ts
// Variable: volunteerGroupSummariesEnQuery
// Query: *[_type == "volunteerGroupSummary"] | order(order asc) {    name,    "description": descriptionEn}
export type VolunteerGroupSummariesEnQueryResult = Array<{
  name: string | null;
  description: string | null;
}>;

// Source: lib/sanity/query-definitions.ts
// Variable: homePageContentNbQuery
// Query: *[_id == "homePage"][0] {    "badge": badgeNb,    "heroDescription": heroDescriptionNb,    "heroDescriptionFusion": heroDescriptionFusionNb,    "eventsLink": eventsLinkNb}
export type HomePageContentNbQueryResult =
  | {
      badge: null;
      heroDescription: null;
      heroDescriptionFusion: null;
      eventsLink: null;
    }
  | {
      badge: string | null;
      heroDescription: string | null;
      heroDescriptionFusion: string | null;
      eventsLink: string | null;
    }
  | null;

// Source: lib/sanity/query-definitions.ts
// Variable: homePageContentEnQuery
// Query: *[_id == "homePage"][0] {    "badge": badgeEn,    "heroDescription": heroDescriptionEn,    "heroDescriptionFusion": heroDescriptionFusionEn,    "eventsLink": eventsLinkEn}
export type HomePageContentEnQueryResult =
  | {
      badge: null;
      heroDescription: null;
      heroDescriptionFusion: null;
      eventsLink: null;
    }
  | {
      badge: string | null;
      heroDescription: string | null;
      heroDescriptionFusion: string | null;
      eventsLink: string | null;
    }
  | null;

// Source: lib/sanity/query-definitions.ts
// Variable: eventsPageContentNbQuery
// Query: *[_id == "eventsPage"][0] {    "eyebrow": eyebrowNb,    "title": titleNb,    "description": descriptionNb}
export type EventsPageContentNbQueryResult =
  | {
      eyebrow: null;
      title: null;
      description: null;
    }
  | {
      eyebrow: string | null;
      title: null;
      description: null;
    }
  | {
      eyebrow: null;
      title: null;
      description: string | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      description: string | null;
    }
  | null;

// Source: lib/sanity/query-definitions.ts
// Variable: eventsPageContentEnQuery
// Query: *[_id == "eventsPage"][0] {    "eyebrow": eyebrowEn,    "title": titleEn,    "description": descriptionEn}
export type EventsPageContentEnQueryResult =
  | {
      eyebrow: null;
      title: null;
      description: null;
    }
  | {
      eyebrow: string | null;
      title: null;
      description: null;
    }
  | {
      eyebrow: null;
      title: null;
      description: string | null;
    }
  | {
      eyebrow: string | null;
      title: string | null;
      description: string | null;
    }
  | null;

// Source: lib/sanity/query-definitions.ts
// Variable: siteMetadataNbQuery
// Query: *[_id == "siteMetadata"][0] {    "siteTitle": siteTitleNb,    "siteDescription": siteDescriptionNb,    "homeTitle": homeTitleNb,    "homeDescription": homeDescriptionNb,    "eventsTitle": eventsTitleNb,    "eventsDescription": eventsDescriptionNb,    "volunteerSignupTitle": volunteerSignupTitleNb,    "volunteerSignupDescription": volunteerSignupDescriptionNb,    "groupPageTitle": groupPageTitleNb,    "groupPageDescription": groupPageDescriptionNb}
export type SiteMetadataNbQueryResult =
  | {
      siteTitle: null;
      siteDescription: null;
      homeTitle: null;
      homeDescription: null;
      eventsTitle: null;
      eventsDescription: null;
      volunteerSignupTitle: null;
      volunteerSignupDescription: null;
      groupPageTitle: null;
      groupPageDescription: null;
    }
  | {
      siteTitle: string | null;
      siteDescription: string | null;
      homeTitle: string | null;
      homeDescription: string | null;
      eventsTitle: string | null;
      eventsDescription: string | null;
      volunteerSignupTitle: string | null;
      volunteerSignupDescription: string | null;
      groupPageTitle: string | null;
      groupPageDescription: string | null;
    }
  | null;

// Source: lib/sanity/query-definitions.ts
// Variable: siteMetadataEnQuery
// Query: *[_id == "siteMetadata"][0] {    "siteTitle": siteTitleEn,    "siteDescription": siteDescriptionEn,    "homeTitle": homeTitleEn,    "homeDescription": homeDescriptionEn,    "eventsTitle": eventsTitleEn,    "eventsDescription": eventsDescriptionEn,    "volunteerSignupTitle": volunteerSignupTitleEn,    "volunteerSignupDescription": volunteerSignupDescriptionEn,    "groupPageTitle": groupPageTitleEn,    "groupPageDescription": groupPageDescriptionEn}
export type SiteMetadataEnQueryResult =
  | {
      siteTitle: null;
      siteDescription: null;
      homeTitle: null;
      homeDescription: null;
      eventsTitle: null;
      eventsDescription: null;
      volunteerSignupTitle: null;
      volunteerSignupDescription: null;
      groupPageTitle: null;
      groupPageDescription: null;
    }
  | {
      siteTitle: string | null;
      siteDescription: string | null;
      homeTitle: string | null;
      homeDescription: string | null;
      eventsTitle: string | null;
      eventsDescription: string | null;
      volunteerSignupTitle: string | null;
      volunteerSignupDescription: string | null;
      groupPageTitle: string | null;
      groupPageDescription: string | null;
    }
  | null;

// Source: lib/sanity/query-definitions.ts
// Variable: homeBarsNbQuery
// Query: *[_type == "homeBar"] | order(order asc) {    "name": nameNb,    "description": descriptionNb,    "imageUrl": image.asset->url}
export type HomeBarsNbQueryResult = Array<{
  name: string | null;
  description: string | null;
  imageUrl: string | null;
}>;

// Source: lib/sanity/query-definitions.ts
// Variable: homeBarsEnQuery
// Query: *[_type == "homeBar"] | order(order asc) {    "name": nameEn,    "description": descriptionEn,    "imageUrl": image.asset->url}
export type HomeBarsEnQueryResult = Array<{
  name: string | null;
  description: string | null;
  imageUrl: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "launchGroup"] | order(_createdAt asc) {\n    slug,\n    "name": nameNb,\n    "eyebrow": eyebrowNb,\n    "lead": leadNb,\n    "imageUrl": image.asset->url,\n    "accordionSections": accordionSections[] {\n        "title": titleNb,\n        "paragraphs": paragraphsNb\n    },\n    "detailSections": detailSections[] {\n        "title": titleNb,\n        "paragraphs": paragraphsNb\n    }\n}': LaunchGroupsNbQueryResult;
    '*[_type == "launchGroup"] | order(_createdAt asc) {\n    slug,\n    "name": nameEn,\n    "eyebrow": eyebrowEn,\n    "lead": leadEn,\n    "imageUrl": image.asset->url,\n    "accordionSections": accordionSections[] {\n        "title": titleEn,\n        "paragraphs": paragraphsEn\n    },\n    "detailSections": detailSections[] {\n        "title": titleEn,\n        "paragraphs": paragraphsEn\n    }\n}': LaunchGroupsEnQueryResult;
    '*[_type == "volunteerGroupSummary"] | order(order asc) {\n    name,\n    "description": descriptionNb\n}': VolunteerGroupSummariesNbQueryResult;
    '*[_type == "volunteerGroupSummary"] | order(order asc) {\n    name,\n    "description": descriptionEn\n}': VolunteerGroupSummariesEnQueryResult;
    '*[_id == "homePage"][0] {\n    "badge": badgeNb,\n    "heroDescription": heroDescriptionNb,\n    "heroDescriptionFusion": heroDescriptionFusionNb,\n    "eventsLink": eventsLinkNb\n}': HomePageContentNbQueryResult;
    '*[_id == "homePage"][0] {\n    "badge": badgeEn,\n    "heroDescription": heroDescriptionEn,\n    "heroDescriptionFusion": heroDescriptionFusionEn,\n    "eventsLink": eventsLinkEn\n}': HomePageContentEnQueryResult;
    '*[_id == "eventsPage"][0] {\n    "eyebrow": eyebrowNb,\n    "title": titleNb,\n    "description": descriptionNb\n}': EventsPageContentNbQueryResult;
    '*[_id == "eventsPage"][0] {\n    "eyebrow": eyebrowEn,\n    "title": titleEn,\n    "description": descriptionEn\n}': EventsPageContentEnQueryResult;
    '*[_id == "siteMetadata"][0] {\n    "siteTitle": siteTitleNb,\n    "siteDescription": siteDescriptionNb,\n    "homeTitle": homeTitleNb,\n    "homeDescription": homeDescriptionNb,\n    "eventsTitle": eventsTitleNb,\n    "eventsDescription": eventsDescriptionNb,\n    "volunteerSignupTitle": volunteerSignupTitleNb,\n    "volunteerSignupDescription": volunteerSignupDescriptionNb,\n    "groupPageTitle": groupPageTitleNb,\n    "groupPageDescription": groupPageDescriptionNb\n}': SiteMetadataNbQueryResult;
    '*[_id == "siteMetadata"][0] {\n    "siteTitle": siteTitleEn,\n    "siteDescription": siteDescriptionEn,\n    "homeTitle": homeTitleEn,\n    "homeDescription": homeDescriptionEn,\n    "eventsTitle": eventsTitleEn,\n    "eventsDescription": eventsDescriptionEn,\n    "volunteerSignupTitle": volunteerSignupTitleEn,\n    "volunteerSignupDescription": volunteerSignupDescriptionEn,\n    "groupPageTitle": groupPageTitleEn,\n    "groupPageDescription": groupPageDescriptionEn\n}': SiteMetadataEnQueryResult;
    '*[_type == "homeBar"] | order(order asc) {\n    "name": nameNb,\n    "description": descriptionNb,\n    "imageUrl": image.asset->url\n}': HomeBarsNbQueryResult;
    '*[_type == "homeBar"] | order(order asc) {\n    "name": nameEn,\n    "description": descriptionEn,\n    "imageUrl": image.asset->url\n}': HomeBarsEnQueryResult;
  }
}
