export type {
  EventDetail,
  EventGroup,
  EventRoom,
  EventsPageContent,
  EventType,
  GroupsPageContent,
  HomePageContent,
  NavbarContent,
  NavGroup,
  NavItem,
  NavLeaf,
  PageContent,
  PublishedEvent,
  RoomDetail,
  RoomSummary,
  RoomsPageContent,
  SiteMetadataContent,
  SourcedImage,
  SponsorsPageContent,
  StudentGroupDetail,
  StudentGroupSummary,
} from "./fetch"
export type {
  Arrangement,
  EventsPage,
  Footer,
  GroupsPage,
  HomePage,
  KontaktPage,
  LinkInBio,
  Navbar,
  Page,
  Room,
  RoomsPage,
  SiteMetadata,
  SponsorsPage,
  StudentGroup,
} from "./sanity.types"
