// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {})
}

/**
 * AcceptedStatusResponse
 */
export type AcceptedStatusResponse = {
    /**
     * Status
     */
    status: "accepted"
}

/**
 * AccessCodeRequest
 */
export type AccessCodeRequest = {
    /**
     * Email
     */
    email: string
}

/**
 * Body_admin_account_create_admin_accounts_post
 */
export type BodyAdminAccountCreateAdminAccountsPost = {
    /**
     * Display Name
     */
    display_name?: string | null
    /**
     * Email
     */
    email: string
    /**
     * Role
     */
    role: string
    /**
     * Username
     */
    username: string
}

/**
 * Body_admin_account_update_admin_accounts__account_id__patch
 */
export type BodyAdminAccountUpdateAdminAccountsAccountIdPatch = {
    /**
     * Display Name
     */
    display_name?: string | null
    /**
     * Email
     */
    email: string
    /**
     * Role
     */
    role: string
    /**
     * Username
     */
    username: string
}

/**
 * Body_courses_add_completion_courses__course_id__completions_post
 */
export type BodyCoursesAddCompletionCoursesCourseIdCompletionsPost = {
    /**
     * Term
     */
    term: number
    /**
     * Volunteer Ids
     */
    volunteer_ids?: Array<number>
    /**
     * Year
     */
    year: number
}

/**
 * Body_courses_create_courses_post
 */
export type BodyCoursesCreateCoursesPost = {
    /**
     * Description
     */
    description?: string | null
    /**
     * Name
     */
    name: string
}

/**
 * Body_courses_update_courses__course_id__patch
 */
export type BodyCoursesUpdateCoursesCourseIdPatch = {
    /**
     * Description
     */
    description?: string | null
    /**
     * Name
     */
    name: string
}

/**
 * Body_feedback_submit_feedback_post
 */
export type BodyFeedbackSubmitFeedbackPost = {
    /**
     * Category
     */
    category: string
    /**
     * Email
     */
    email?: string | null
    /**
     * Message
     */
    message: string
    /**
     * Name
     */
    name?: string | null
    /**
     * Page
     */
    page: string
}

/**
 * Body_group_role_assignments_create_groups__group_id__role_assignments_post
 */
export type BodyGroupRoleAssignmentsCreateGroupsGroupIdRoleAssignmentsPost = {
    /**
     * Contract Signed
     */
    contract_signed?: boolean
    /**
     * Role Id
     */
    role_id: number
    /**
     * Term
     */
    term: number
    /**
     * Volunteer Ids
     */
    volunteer_ids?: Array<number>
    /**
     * Year
     */
    year: number
}

/**
 * Body_group_roles_create_groups__group_id__roles_post
 */
export type BodyGroupRolesCreateGroupsGroupIdRolesPost = {
    /**
     * Pingvin Points
     */
    pingvin_points: number
    /**
     * Role Name
     */
    role_name: string
}

/**
 * Body_group_roles_update_groups__group_id__roles__role_id__patch
 */
export type BodyGroupRolesUpdateGroupsGroupIdRolesRoleIdPatch = {
    /**
     * Pingvin Points
     */
    pingvin_points: number
    /**
     * Role Name
     */
    role_name: string
}

/**
 * Body_groups_apply_semester_transfer_groups__group_id__semester_transfer_post
 */
export type BodyGroupsApplySemesterTransferGroupsGroupIdSemesterTransferPost = {
    /**
     * Role Ids
     */
    role_ids?: Array<string>
    /**
     * Target Semester
     */
    target_semester: number
    /**
     * Volunteer Ids
     */
    volunteer_ids?: Array<number>
}

/**
 * Body_groups_create_groups_post
 */
export type BodyGroupsCreateGroupsPost = {
    /**
     * Active
     */
    active?: string | null
    /**
     * Active Until Semester
     */
    active_until_semester: number
    /**
     * Description
     */
    description?: string | null
    /**
     * Discount Step
     */
    discount_step?: string | null
    /**
     * Name
     */
    name: string
    /**
     * Parent Group Id
     */
    parent_group_id?: string | null
}

/**
 * Body_groups_update_groups__group_id__patch
 */
export type BodyGroupsUpdateGroupsGroupIdPatch = {
    /**
     * Active
     */
    active?: string | null
    /**
     * Active Until Semester
     */
    active_until_semester: number
    /**
     * Description
     */
    description?: string | null
    /**
     * Discount Step
     */
    discount_step?: string | null
    /**
     * Name
     */
    name: string
    /**
     * Parent Group Id
     */
    parent_group_id?: string | null
}

/**
 * Body_login_submit_login_post
 */
export type BodyLoginSubmitLoginPost = {
    /**
     * Identifier
     */
    identifier: string
    /**
     * Password
     */
    password: string
}

/**
 * Body_mobile_card_april_state_update_mobile_card_april_state_post
 */
export type BodyMobileCardAprilStateUpdateMobileCardAprilStatePost = {
    /**
     * Enabled
     */
    enabled: string
}

/**
 * Body_my_account_change_password_my_account_password_post
 */
export type BodyMyAccountChangePasswordMyAccountPasswordPost = {
    /**
     * Confirm Password
     */
    confirm_password: string
    /**
     * Current Password
     */
    current_password: string
    /**
     * New Password
     */
    new_password: string
}

/**
 * Body_my_account_update_my_account_patch
 */
export type BodyMyAccountUpdateMyAccountPatch = {
    /**
     * Display Name
     */
    display_name?: string | null
    /**
     * Email
     */
    email: string
    /**
     * Role
     */
    role: string
    /**
     * Username
     */
    username: string
}

/**
 * Body_set_password_submit_set_password_post
 */
export type BodySetPasswordSubmitSetPasswordPost = {
    /**
     * Access Token
     */
    access_token: string
    /**
     * Confirm Password
     */
    confirm_password: string
    /**
     * Password
     */
    password: string
}

/**
 * Body_volunteer_add_course_completion_volunteers__volunteer_id__course_completions_post
 */
export type BodyVolunteerAddCourseCompletionVolunteersVolunteerIdCourseCompletionsPost = {
    /**
     * Course Id
     */
    course_id: number
    /**
     * Term
     */
    term: number
    /**
     * Year
     */
    year: number
}

/**
 * Body_volunteer_add_role_assignment_volunteers__volunteer_id__role_assignments_post
 */
export type BodyVolunteerAddRoleAssignmentVolunteersVolunteerIdRoleAssignmentsPost = {
    /**
     * Contract Signed
     */
    contract_signed?: boolean
    /**
     * Group Id
     */
    group_id: number
    /**
     * Role Id
     */
    role_id: number
    /**
     * Term
     */
    term: number
    /**
     * Year
     */
    year: number
}

/**
 * Body_volunteer_application_approve_volunteer_applications__application_id__approval_post
 */
export type BodyVolunteerApplicationApproveVolunteerApplicationsApplicationIdApprovalPost = {
    /**
     * Accepted Group Id
     */
    accepted_group_id?: string | null
}

/**
 * Body_volunteer_application_mark_trial_attendance_volunteer_applications__application_id__trial_attendance_post
 */
export type BodyVolunteerApplicationMarkTrialAttendanceVolunteerApplicationsApplicationIdTrialAttendancePost =
    {
        /**
         * Attended
         */
        attended: string
    }

/**
 * Body_volunteer_application_submit_apply__token__post
 */
export type BodyVolunteerApplicationSubmitApplyTokenPost = {
    /**
     * Address
     */
    address?: string | null
    /**
     * Birth Date
     */
    birth_date?: string | null
    /**
     * First Name
     */
    first_name?: string | null
    /**
     * Gender
     */
    gender?: string
    /**
     * Last Name
     */
    last_name: string
    /**
     * Phone
     */
    phone: string
    /**
     * Postal Code
     */
    postal_code?: string | null
    /**
     * Profile Photo
     */
    profile_photo?: Blob | File | null
}

/**
 * Body_volunteer_applications_create_invite_volunteer_applications_post
 */
export type BodyVolunteerApplicationsCreateInviteVolunteerApplicationsPost = {
    /**
     * Email
     */
    email: string
    /**
     * Group Id
     */
    group_id?: string | null
    /**
     * Role Id
     */
    role_id?: string | null
}

/**
 * Body_volunteer_update_profile_volunteers__volunteer_id__patch
 */
export type BodyVolunteerUpdateProfileVolunteersVolunteerIdPatch = {
    /**
     * Address
     */
    address?: string | null
    /**
     * Birth Date
     */
    birth_date?: string | null
    /**
     * Email
     */
    email?: string | null
    /**
     * First Name
     */
    first_name?: string | null
    /**
     * Gender
     */
    gender?: string
    /**
     * Last Name
     */
    last_name: string
    /**
     * Phone
     */
    phone?: string | null
    /**
     * Postal Code
     */
    postal_code?: string | null
}

/**
 * Body_volunteer_update_role_assignment_volunteers__volunteer_id__role_assignments__assignment_id__patch
 */
export type BodyVolunteerUpdateRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdPatch =
    {
        /**
         * Contract Signed
         */
        contract_signed?: boolean
        /**
         * Group Id
         */
        group_id: number
        /**
         * Role Id
         */
        role_id: number
        /**
         * Term
         */
        term: number
        /**
         * Year
         */
        year: number
    }

/**
 * Body_volunteer_upload_photo_volunteers__volunteer_id__photo_post
 */
export type BodyVolunteerUploadPhotoVolunteersVolunteerIdPhotoPost = {
    /**
     * Photo
     */
    photo: Blob | File
}

/**
 * EventDetail
 */
export type EventDetail = {
    /**
     * Created At
     */
    created_at: string
    /**
     * Description
     */
    description?: string | null
    /**
     * Ends At
     */
    ends_at: string
    event_type?: EventType | null
    /**
     * Event Type Id
     */
    event_type_id: string
    /**
     * Facebook Url
     */
    facebook_url?: string | null
    /**
     * Id
     */
    id: string
    /**
     * Image Caption
     */
    image_caption?: string | null
    /**
     * Image Url
     */
    image_url?: string | null
    /**
     * Is Featured
     */
    is_featured: boolean
    /**
     * Is Internal
     */
    is_internal: boolean
    /**
     * Language
     */
    language: "no" | "en"
    /**
     * Organizer Groups
     */
    organizer_groups: Array<EventOrganizerGroup>
    /**
     * Price
     */
    price?: string | null
    /**
     * Recurring Interval Days
     */
    recurring_interval_days?: number | null
    room?: EventRoom | null
    /**
     * Room Id
     */
    room_id?: string | null
    /**
     * Room Text
     */
    room_text?: string | null
    /**
     * Slug
     */
    slug: string
    /**
     * Starts At
     */
    starts_at: string
    /**
     * Status
     */
    status: "published" | "draft" | "archived"
    /**
     * Ticket Url
     */
    ticket_url?: string | null
    /**
     * Title
     */
    title: string
    translations: EventTranslations
    /**
     * Updated At
     */
    updated_at: string
}

/**
 * EventList
 */
export type EventList = {
    /**
     * Events
     */
    events: Array<EventDetail>
}

/**
 * EventOrganizerGroup
 */
export type EventOrganizerGroup = {
    /**
     * Default Event Type Id
     */
    default_event_type_id?: string | null
    /**
     * Id
     */
    id: string
    /**
     * Is Active
     */
    is_active: boolean
    /**
     * Name
     */
    name: string
    /**
     * Slug
     */
    slug: string
    /**
     * Sort Order
     */
    sort_order: number
}

/**
 * EventRoom
 */
export type EventRoom = {
    /**
     * Id
     */
    id: string
    /**
     * Is Active
     */
    is_active: boolean
    /**
     * Name
     */
    name: string
    /**
     * Slug
     */
    slug: string
    /**
     * Sort Order
     */
    sort_order: number
}

/**
 * EventTaxonomy
 */
export type EventTaxonomy = {
    /**
     * Event Type Groups
     */
    event_type_groups: Array<EventTypeGroup>
    /**
     * Organizer Groups
     */
    organizer_groups: Array<EventOrganizerGroup>
    /**
     * Rooms
     */
    rooms: Array<EventRoom>
}

/**
 * EventTranslation
 */
export type EventTranslation = {
    /**
     * Available
     */
    available?: boolean
    /**
     * Description
     */
    description?: string | null
    /**
     * Image Caption
     */
    image_caption?: string | null
    /**
     * Title
     */
    title: string
}

/**
 * EventTranslations
 */
export type EventTranslations = {
    en?: EventTranslation | null
    no?: EventTranslation | null
}

/**
 * EventType
 */
export type EventType = {
    /**
     * Description
     */
    description?: string | null
    /**
     * Id
     */
    id: string
    /**
     * Is Active
     */
    is_active: boolean
    /**
     * Name
     */
    name: string
    /**
     * Slug
     */
    slug: string
    /**
     * Sort Order
     */
    sort_order: number
    /**
     * Taxonomy Group
     */
    taxonomy_group: string
}

/**
 * EventTypeGroup
 */
export type EventTypeGroup = {
    /**
     * Event Types
     */
    event_types: Array<EventType>
    /**
     * Name
     */
    name: string
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>
}

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string
}

/**
 * LegacyDigitalInternKortRequest
 */
export type LegacyDigitalInternKortRequest = {
    /**
     * Accesstoken
     */
    accessToken?: string | null
    /**
     * Email
     */
    email: string
}

/**
 * MobileCardResponse
 */
export type MobileCardResponse = {
    /**
     * Active Roles
     */
    active_roles: Array<MobileCardRole>
    /**
     * Birth Date
     */
    birth_date?: string | null
    /**
     * Created At
     */
    created_at: string
    /**
     * First Name
     */
    first_name: string
    /**
     * Last Name
     */
    last_name: string
    /**
     * Person Id
     */
    person_id: number
    /**
     * Photo Url
     */
    photo_url?: string | null
    /**
     * Pingvin Points
     */
    pingvin_points: number
    /**
     * Valid Until
     */
    valid_until: string
    /**
     * Word Of The Day
     */
    word_of_the_day: string
}

/**
 * MobileCardRole
 */
export type MobileCardRole = {
    /**
     * Discount Level
     */
    discount_level?: number | null
    /**
     * Group
     */
    group: string
    /**
     * Name
     */
    name: string
    /**
     * Pingvin Points
     */
    pingvin_points?: number
    /**
     * Signed Contract
     */
    signed_contract?: boolean
}

/**
 * MobileCardSessionCreateRequest
 */
export type MobileCardSessionCreateRequest = {
    /**
     * Access Code
     */
    access_code: string
    /**
     * Email
     */
    email: string
}

/**
 * MobileCardSessionLogoutEventRequest
 */
export type MobileCardSessionLogoutEventRequest = {
    /**
     * App Version
     */
    app_version?: string | null
    /**
     * Auth Error Code
     */
    auth_error_code?: string | null
    /**
     * Auth Error Message
     */
    auth_error_message?: string | null
    /**
     * Auth Error Status
     */
    auth_error_status?: number | null
    /**
     * Cached User Id
     */
    cached_user_id?: number | null
    /**
     * Event Name
     */
    event_name: "credentials_missing_after_login" | "session_invalidated"
    /**
     * Execution Environment
     */
    execution_environment?: string | null
    /**
     * Had Cached User
     */
    had_cached_user: boolean
    /**
     * Had Login Marker
     */
    had_login_marker: boolean
    /**
     * Had Stored Credentials
     */
    had_stored_credentials: boolean
    /**
     * Occurred At
     */
    occurred_at: string
    /**
     * Platform
     */
    platform: string
    /**
     * Runtime Version
     */
    runtime_version?: string | null
    /**
     * Update Channel
     */
    update_channel?: string | null
    /**
     * Update Id
     */
    update_id?: string | null
}

/**
 * MobileCardSessionResponse
 */
export type MobileCardSessionResponse = {
    card: MobileCardResponse
    /**
     * Session Token
     */
    session_token: string
}

/**
 * NowPlayingStateResponse
 */
export type NowPlayingStateResponse = {
    /**
     * Album
     */
    album?: string | null
    /**
     * Artists
     */
    artists?: string | null
    /**
     * Authorized
     */
    authorized: boolean
    /**
     * Connecturl
     */
    connectUrl: string
    /**
     * Durationms
     */
    durationMs?: number | null
    /**
     * Hastrack
     */
    hasTrack: boolean
    /**
     * Image
     */
    image?: string | null
    /**
     * Isplaybackactive
     */
    isPlaybackActive: boolean
    /**
     * Name
     */
    name?: string | null
    /**
     * Progressms
     */
    progressMs?: number | null
    /**
     * Progresspercent
     */
    progressPercent?: number | null
}

/**
 * PublicVolunteerProspectRequest
 */
export type PublicVolunteerProspectRequest = {
    /**
     * Background Details
     */
    background_details?: string | null
    /**
     * Email
     */
    email: string
    /**
     * First Choice Group Slug
     */
    first_choice_group_slug: string
    /**
     * Full Name
     */
    full_name: string
    /**
     * Phone
     */
    phone: string
    /**
     * Second Choice Group Slug
     */
    second_choice_group_slug?: string | null
    /**
     * Study Institution
     */
    study_institution: string
}

/**
 * PublicVolunteerProspectResponse
 */
export type PublicVolunteerProspectResponse = {
    /**
     * Registrationid
     */
    registrationId: number
}

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown
    }
    /**
     * Input
     */
    input?: unknown
    /**
     * Location
     */
    loc: Array<string | number>
    /**
     * Message
     */
    msg: string
    /**
     * Error Type
     */
    type: string
}

export type DashboardGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Mobile Card April Message
         */
        mobile_card_april_message?: string | null
    }
    url: "/"
}

export type DashboardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type DashboardGetError = DashboardGetErrors[keyof DashboardGetErrors]

export type DashboardGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type AdminAccountsIndexAdminAccountsGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Q
         */
        q?: string | null
    }
    url: "/admin-accounts"
}

export type AdminAccountsIndexAdminAccountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminAccountsIndexAdminAccountsGetError =
    AdminAccountsIndexAdminAccountsGetErrors[keyof AdminAccountsIndexAdminAccountsGetErrors]

export type AdminAccountsIndexAdminAccountsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type AdminAccountCreateAdminAccountsPostData = {
    body: BodyAdminAccountCreateAdminAccountsPost
    path?: never
    query?: never
    url: "/admin-accounts"
}

export type AdminAccountCreateAdminAccountsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminAccountCreateAdminAccountsPostError =
    AdminAccountCreateAdminAccountsPostErrors[keyof AdminAccountCreateAdminAccountsPostErrors]

export type AdminAccountCreateAdminAccountsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type AdminAccountNewAdminAccountsNewGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Error
         */
        error?: string | null
    }
    url: "/admin-accounts/new"
}

export type AdminAccountNewAdminAccountsNewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminAccountNewAdminAccountsNewGetError =
    AdminAccountNewAdminAccountsNewGetErrors[keyof AdminAccountNewAdminAccountsNewGetErrors]

export type AdminAccountNewAdminAccountsNewGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type AdminAccountDeleteAdminAccountsAccountIdDeleteData = {
    body?: never
    path: {
        /**
         * Account Id
         */
        account_id: number
    }
    query?: never
    url: "/admin-accounts/{account_id}"
}

export type AdminAccountDeleteAdminAccountsAccountIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminAccountDeleteAdminAccountsAccountIdDeleteError =
    AdminAccountDeleteAdminAccountsAccountIdDeleteErrors[keyof AdminAccountDeleteAdminAccountsAccountIdDeleteErrors]

export type AdminAccountDeleteAdminAccountsAccountIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type AdminAccountDetailAdminAccountsAccountIdGetData = {
    body?: never
    path: {
        /**
         * Account Id
         */
        account_id: number
    }
    query?: {
        /**
         * Error
         */
        error?: string | null
    }
    url: "/admin-accounts/{account_id}"
}

export type AdminAccountDetailAdminAccountsAccountIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminAccountDetailAdminAccountsAccountIdGetError =
    AdminAccountDetailAdminAccountsAccountIdGetErrors[keyof AdminAccountDetailAdminAccountsAccountIdGetErrors]

export type AdminAccountDetailAdminAccountsAccountIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type AdminAccountUpdateAdminAccountsAccountIdPatchData = {
    body: BodyAdminAccountUpdateAdminAccountsAccountIdPatch
    path: {
        /**
         * Account Id
         */
        account_id: number
    }
    query?: never
    url: "/admin-accounts/{account_id}"
}

export type AdminAccountUpdateAdminAccountsAccountIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminAccountUpdateAdminAccountsAccountIdPatchError =
    AdminAccountUpdateAdminAccountsAccountIdPatchErrors[keyof AdminAccountUpdateAdminAccountsAccountIdPatchErrors]

export type AdminAccountUpdateAdminAccountsAccountIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type AdminAccountImpersonateAdminAccountsAccountIdImpersonatePostData = {
    body?: never
    path: {
        /**
         * Account Id
         */
        account_id: number
    }
    query?: never
    url: "/admin-accounts/{account_id}/impersonate"
}

export type AdminAccountImpersonateAdminAccountsAccountIdImpersonatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminAccountImpersonateAdminAccountsAccountIdImpersonatePostError =
    AdminAccountImpersonateAdminAccountsAccountIdImpersonatePostErrors[keyof AdminAccountImpersonateAdminAccountsAccountIdImpersonatePostErrors]

export type AdminAccountImpersonateAdminAccountsAccountIdImpersonatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type LegacyGetMobileCardInformationData = {
    body: LegacyDigitalInternKortRequest
    path?: never
    query?: never
    url: "/api/DigitalInternkort/GetInternkortInformation"
}

export type LegacyGetMobileCardInformationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type LegacyGetMobileCardInformationError =
    LegacyGetMobileCardInformationErrors[keyof LegacyGetMobileCardInformationErrors]

export type LegacyGetMobileCardInformationResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type LegacyRequestMobileCardAccessTokenOnEmailData = {
    body: LegacyDigitalInternKortRequest
    path?: never
    query?: never
    url: "/api/DigitalInternkort/RequestAccessTokenOnEmail"
}

export type LegacyRequestMobileCardAccessTokenOnEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type LegacyRequestMobileCardAccessTokenOnEmailError =
    LegacyRequestMobileCardAccessTokenOnEmailErrors[keyof LegacyRequestMobileCardAccessTokenOnEmailErrors]

export type LegacyRequestMobileCardAccessTokenOnEmailResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GetNowPlayingData = {
    body?: never
    path?: never
    query?: never
    url: "/api/now-playing"
}

export type GetNowPlayingResponses = {
    /**
     * Successful Response
     */
    200: NowPlayingStateResponse
}

export type GetNowPlayingResponse = GetNowPlayingResponses[keyof GetNowPlayingResponses]

export type ListEventsData = {
    body?: never
    headers?: {
        /**
         * Accept-Language
         */
        "accept-language"?: string | null
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: {
        /**
         * Include Internal
         */
        include_internal?: boolean
        /**
         * Limit
         */
        limit?: number
    }
    url: "/api/v1/events"
}

export type ListEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type ListEventsError = ListEventsErrors[keyof ListEventsErrors]

export type ListEventsResponses = {
    /**
     * Successful Response
     */
    200: EventList
}

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses]

export type GetEventTaxonomyData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/events/taxonomy"
}

export type GetEventTaxonomyResponses = {
    /**
     * Successful Response
     */
    200: EventTaxonomy
}

export type GetEventTaxonomyResponse = GetEventTaxonomyResponses[keyof GetEventTaxonomyResponses]

export type GetEventData = {
    body?: never
    headers?: {
        /**
         * Accept-Language
         */
        "accept-language"?: string | null
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Event Id
         */
        event_id: string
    }
    query?: never
    url: "/api/v1/events/{event_id}"
}

export type GetEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetEventError = GetEventErrors[keyof GetEventErrors]

export type GetEventResponses = {
    /**
     * Successful Response
     */
    200: EventDetail
}

export type GetEventResponse = GetEventResponses[keyof GetEventResponses]

export type RequestMobileCardAccessCodeData = {
    body: AccessCodeRequest
    path?: never
    query?: never
    url: "/api/v1/mobile-card/access-codes"
}

export type RequestMobileCardAccessCodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type RequestMobileCardAccessCodeError =
    RequestMobileCardAccessCodeErrors[keyof RequestMobileCardAccessCodeErrors]

export type RequestMobileCardAccessCodeResponses = {
    /**
     * Successful Response
     */
    202: AcceptedStatusResponse
}

export type RequestMobileCardAccessCodeResponse =
    RequestMobileCardAccessCodeResponses[keyof RequestMobileCardAccessCodeResponses]

export type LogMobileCardSessionLogoutEventData = {
    body: MobileCardSessionLogoutEventRequest
    path?: never
    query?: never
    url: "/api/v1/mobile-card/client-events/session-logout"
}

export type LogMobileCardSessionLogoutEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type LogMobileCardSessionLogoutEventError =
    LogMobileCardSessionLogoutEventErrors[keyof LogMobileCardSessionLogoutEventErrors]

export type LogMobileCardSessionLogoutEventResponses = {
    /**
     * Successful Response
     */
    202: AcceptedStatusResponse
}

export type LogMobileCardSessionLogoutEventResponse =
    LogMobileCardSessionLogoutEventResponses[keyof LogMobileCardSessionLogoutEventResponses]

export type GetCurrentMobileCardData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/api/v1/mobile-card/me"
}

export type GetCurrentMobileCardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetCurrentMobileCardError = GetCurrentMobileCardErrors[keyof GetCurrentMobileCardErrors]

export type GetCurrentMobileCardResponses = {
    /**
     * Successful Response
     */
    200: MobileCardResponse
}

export type GetCurrentMobileCardResponse =
    GetCurrentMobileCardResponses[keyof GetCurrentMobileCardResponses]

export type CreateMobileCardSessionData = {
    body: MobileCardSessionCreateRequest
    path?: never
    query?: never
    url: "/api/v1/mobile-card/sessions"
}

export type CreateMobileCardSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateMobileCardSessionError =
    CreateMobileCardSessionErrors[keyof CreateMobileCardSessionErrors]

export type CreateMobileCardSessionResponses = {
    /**
     * Successful Response
     */
    200: MobileCardSessionResponse
}

export type CreateMobileCardSessionResponse =
    CreateMobileCardSessionResponses[keyof CreateMobileCardSessionResponses]

export type CreatePublicVolunteerProspectData = {
    body: PublicVolunteerProspectRequest
    path?: never
    query?: never
    url: "/api/v1/volunteer-prospects"
}

export type CreatePublicVolunteerProspectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreatePublicVolunteerProspectError =
    CreatePublicVolunteerProspectErrors[keyof CreatePublicVolunteerProspectErrors]

export type CreatePublicVolunteerProspectResponses = {
    /**
     * Successful Response
     */
    201: PublicVolunteerProspectResponse
}

export type CreatePublicVolunteerProspectResponse =
    CreatePublicVolunteerProspectResponses[keyof CreatePublicVolunteerProspectResponses]

export type VolunteerApplicationFormApplyTokenGetData = {
    body?: never
    path: {
        /**
         * Token
         */
        token: string
    }
    query?: never
    url: "/apply/{token}"
}

export type VolunteerApplicationFormApplyTokenGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationFormApplyTokenGetError =
    VolunteerApplicationFormApplyTokenGetErrors[keyof VolunteerApplicationFormApplyTokenGetErrors]

export type VolunteerApplicationFormApplyTokenGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationSubmitApplyTokenPostData = {
    body: BodyVolunteerApplicationSubmitApplyTokenPost
    path: {
        /**
         * Token
         */
        token: string
    }
    query?: never
    url: "/apply/{token}"
}

export type VolunteerApplicationSubmitApplyTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationSubmitApplyTokenPostError =
    VolunteerApplicationSubmitApplyTokenPostErrors[keyof VolunteerApplicationSubmitApplyTokenPostErrors]

export type VolunteerApplicationSubmitApplyTokenPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationSubmittedApplyTokenSubmittedGetData = {
    body?: never
    path: {
        /**
         * Token
         */
        token: string
    }
    query?: never
    url: "/apply/{token}/submitted"
}

export type VolunteerApplicationSubmittedApplyTokenSubmittedGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationSubmittedApplyTokenSubmittedGetError =
    VolunteerApplicationSubmittedApplyTokenSubmittedGetErrors[keyof VolunteerApplicationSubmittedApplyTokenSubmittedGetErrors]

export type VolunteerApplicationSubmittedApplyTokenSubmittedGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type CoursesIndexCoursesGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Q
         */
        q?: string | null
    }
    url: "/courses"
}

export type CoursesIndexCoursesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CoursesIndexCoursesGetError =
    CoursesIndexCoursesGetErrors[keyof CoursesIndexCoursesGetErrors]

export type CoursesIndexCoursesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type CoursesCreateCoursesPostData = {
    body: BodyCoursesCreateCoursesPost
    path?: never
    query?: never
    url: "/courses"
}

export type CoursesCreateCoursesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CoursesCreateCoursesPostError =
    CoursesCreateCoursesPostErrors[keyof CoursesCreateCoursesPostErrors]

export type CoursesCreateCoursesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type CoursesNewCoursesNewGetData = {
    body?: never
    path?: never
    query?: never
    url: "/courses/new"
}

export type CoursesNewCoursesNewGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type CoursesDeleteCoursesCourseIdDeleteData = {
    body?: never
    path: {
        /**
         * Course Id
         */
        course_id: number
    }
    query?: never
    url: "/courses/{course_id}"
}

export type CoursesDeleteCoursesCourseIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CoursesDeleteCoursesCourseIdDeleteError =
    CoursesDeleteCoursesCourseIdDeleteErrors[keyof CoursesDeleteCoursesCourseIdDeleteErrors]

export type CoursesDeleteCoursesCourseIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type CoursesDetailCoursesCourseIdGetData = {
    body?: never
    path: {
        /**
         * Course Id
         */
        course_id: number
    }
    query?: never
    url: "/courses/{course_id}"
}

export type CoursesDetailCoursesCourseIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CoursesDetailCoursesCourseIdGetError =
    CoursesDetailCoursesCourseIdGetErrors[keyof CoursesDetailCoursesCourseIdGetErrors]

export type CoursesDetailCoursesCourseIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type CoursesUpdateCoursesCourseIdPatchData = {
    body: BodyCoursesUpdateCoursesCourseIdPatch
    path: {
        /**
         * Course Id
         */
        course_id: number
    }
    query?: never
    url: "/courses/{course_id}"
}

export type CoursesUpdateCoursesCourseIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CoursesUpdateCoursesCourseIdPatchError =
    CoursesUpdateCoursesCourseIdPatchErrors[keyof CoursesUpdateCoursesCourseIdPatchErrors]

export type CoursesUpdateCoursesCourseIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type CoursesAddCompletionCoursesCourseIdCompletionsPostData = {
    body: BodyCoursesAddCompletionCoursesCourseIdCompletionsPost
    path: {
        /**
         * Course Id
         */
        course_id: number
    }
    query?: never
    url: "/courses/{course_id}/completions"
}

export type CoursesAddCompletionCoursesCourseIdCompletionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CoursesAddCompletionCoursesCourseIdCompletionsPostError =
    CoursesAddCompletionCoursesCourseIdCompletionsPostErrors[keyof CoursesAddCompletionCoursesCourseIdCompletionsPostErrors]

export type CoursesAddCompletionCoursesCourseIdCompletionsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type CoursesDeleteCompletionCoursesCourseIdCompletionsCompletionIdDeleteData = {
    body?: never
    path: {
        /**
         * Course Id
         */
        course_id: number
        /**
         * Completion Id
         */
        completion_id: number
    }
    query?: never
    url: "/courses/{course_id}/completions/{completion_id}"
}

export type CoursesDeleteCompletionCoursesCourseIdCompletionsCompletionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CoursesDeleteCompletionCoursesCourseIdCompletionsCompletionIdDeleteError =
    CoursesDeleteCompletionCoursesCourseIdCompletionsCompletionIdDeleteErrors[keyof CoursesDeleteCompletionCoursesCourseIdCompletionsCompletionIdDeleteErrors]

export type CoursesDeleteCompletionCoursesCourseIdCompletionsCompletionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type FeedbackSubmitFeedbackPostData = {
    body: BodyFeedbackSubmitFeedbackPost
    path?: never
    query?: never
    url: "/feedback"
}

export type FeedbackSubmitFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type FeedbackSubmitFeedbackPostError =
    FeedbackSubmitFeedbackPostErrors[keyof FeedbackSubmitFeedbackPostErrors]

export type FeedbackSubmitFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: string
}

export type FeedbackSubmitFeedbackPostResponse =
    FeedbackSubmitFeedbackPostResponses[keyof FeedbackSubmitFeedbackPostResponses]

export type FeedbackDismissFeedbackDismissGetData = {
    body?: never
    path?: never
    query?: never
    url: "/feedback/dismiss"
}

export type FeedbackDismissFeedbackDismissGetResponses = {
    /**
     * Successful Response
     */
    200: string
}

export type FeedbackDismissFeedbackDismissGetResponse =
    FeedbackDismissFeedbackDismissGetResponses[keyof FeedbackDismissFeedbackDismissGetResponses]

export type FeedbackPanelFeedbackPanelGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Page
         */
        page?: string | null
    }
    url: "/feedback/panel"
}

export type FeedbackPanelFeedbackPanelGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type FeedbackPanelFeedbackPanelGetError =
    FeedbackPanelFeedbackPanelGetErrors[keyof FeedbackPanelFeedbackPanelGetErrors]

export type FeedbackPanelFeedbackPanelGetResponses = {
    /**
     * Successful Response
     */
    200: string
}

export type FeedbackPanelFeedbackPanelGetResponse =
    FeedbackPanelFeedbackPanelGetResponses[keyof FeedbackPanelFeedbackPanelGetResponses]

export type GroupsIndexGroupsGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Q
         */
        q?: string | null
    }
    url: "/groups"
}

export type GroupsIndexGroupsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsIndexGroupsGetError = GroupsIndexGroupsGetErrors[keyof GroupsIndexGroupsGetErrors]

export type GroupsIndexGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsCreateGroupsPostData = {
    body: BodyGroupsCreateGroupsPost
    path?: never
    query?: never
    url: "/groups"
}

export type GroupsCreateGroupsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsCreateGroupsPostError =
    GroupsCreateGroupsPostErrors[keyof GroupsCreateGroupsPostErrors]

export type GroupsCreateGroupsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsNewGroupsNewGetData = {
    body?: never
    path?: never
    query?: never
    url: "/groups/new"
}

export type GroupsNewGroupsNewGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsDeleteGroupsGroupIdDeleteData = {
    body?: never
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}"
}

export type GroupsDeleteGroupsGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsDeleteGroupsGroupIdDeleteError =
    GroupsDeleteGroupsGroupIdDeleteErrors[keyof GroupsDeleteGroupsGroupIdDeleteErrors]

export type GroupsDeleteGroupsGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsDetailGroupsGroupIdGetData = {
    body?: never
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}"
}

export type GroupsDetailGroupsGroupIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsDetailGroupsGroupIdGetError =
    GroupsDetailGroupsGroupIdGetErrors[keyof GroupsDetailGroupsGroupIdGetErrors]

export type GroupsDetailGroupsGroupIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsUpdateGroupsGroupIdPatchData = {
    body: BodyGroupsUpdateGroupsGroupIdPatch
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}"
}

export type GroupsUpdateGroupsGroupIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsUpdateGroupsGroupIdPatchError =
    GroupsUpdateGroupsGroupIdPatchErrors[keyof GroupsUpdateGroupsGroupIdPatchErrors]

export type GroupsUpdateGroupsGroupIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsArchiveGroupsGroupIdArchivePostData = {
    body?: never
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}/archive"
}

export type GroupsArchiveGroupsGroupIdArchivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsArchiveGroupsGroupIdArchivePostError =
    GroupsArchiveGroupsGroupIdArchivePostErrors[keyof GroupsArchiveGroupsGroupIdArchivePostErrors]

export type GroupsArchiveGroupsGroupIdArchivePostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsDetailHistoryGroupsGroupIdHistoryGetData = {
    body?: never
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}/history"
}

export type GroupsDetailHistoryGroupsGroupIdHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsDetailHistoryGroupsGroupIdHistoryGetError =
    GroupsDetailHistoryGroupsGroupIdHistoryGetErrors[keyof GroupsDetailHistoryGroupsGroupIdHistoryGetErrors]

export type GroupsDetailHistoryGroupsGroupIdHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupHistoryDeleteGroupsGroupIdHistoryHistoryIdDeleteData = {
    body?: never
    path: {
        /**
         * Group Id
         */
        group_id: number
        /**
         * History Id
         */
        history_id: number
    }
    query?: never
    url: "/groups/{group_id}/history/{history_id}"
}

export type GroupHistoryDeleteGroupsGroupIdHistoryHistoryIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupHistoryDeleteGroupsGroupIdHistoryHistoryIdDeleteError =
    GroupHistoryDeleteGroupsGroupIdHistoryHistoryIdDeleteErrors[keyof GroupHistoryDeleteGroupsGroupIdHistoryHistoryIdDeleteErrors]

export type GroupHistoryDeleteGroupsGroupIdHistoryHistoryIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupRoleAssignmentsCreateGroupsGroupIdRoleAssignmentsPostData = {
    body: BodyGroupRoleAssignmentsCreateGroupsGroupIdRoleAssignmentsPost
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}/role-assignments"
}

export type GroupRoleAssignmentsCreateGroupsGroupIdRoleAssignmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupRoleAssignmentsCreateGroupsGroupIdRoleAssignmentsPostError =
    GroupRoleAssignmentsCreateGroupsGroupIdRoleAssignmentsPostErrors[keyof GroupRoleAssignmentsCreateGroupsGroupIdRoleAssignmentsPostErrors]

export type GroupRoleAssignmentsCreateGroupsGroupIdRoleAssignmentsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupRolesCreateGroupsGroupIdRolesPostData = {
    body: BodyGroupRolesCreateGroupsGroupIdRolesPost
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}/roles"
}

export type GroupRolesCreateGroupsGroupIdRolesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupRolesCreateGroupsGroupIdRolesPostError =
    GroupRolesCreateGroupsGroupIdRolesPostErrors[keyof GroupRolesCreateGroupsGroupIdRolesPostErrors]

export type GroupRolesCreateGroupsGroupIdRolesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupRolesDeleteGroupsGroupIdRolesRoleIdDeleteData = {
    body?: never
    path: {
        /**
         * Group Id
         */
        group_id: number
        /**
         * Role Id
         */
        role_id: number
    }
    query?: never
    url: "/groups/{group_id}/roles/{role_id}"
}

export type GroupRolesDeleteGroupsGroupIdRolesRoleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupRolesDeleteGroupsGroupIdRolesRoleIdDeleteError =
    GroupRolesDeleteGroupsGroupIdRolesRoleIdDeleteErrors[keyof GroupRolesDeleteGroupsGroupIdRolesRoleIdDeleteErrors]

export type GroupRolesDeleteGroupsGroupIdRolesRoleIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupRolesUpdateGroupsGroupIdRolesRoleIdPatchData = {
    body: BodyGroupRolesUpdateGroupsGroupIdRolesRoleIdPatch
    path: {
        /**
         * Group Id
         */
        group_id: number
        /**
         * Role Id
         */
        role_id: number
    }
    query?: never
    url: "/groups/{group_id}/roles/{role_id}"
}

export type GroupRolesUpdateGroupsGroupIdRolesRoleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupRolesUpdateGroupsGroupIdRolesRoleIdPatchError =
    GroupRolesUpdateGroupsGroupIdRolesRoleIdPatchErrors[keyof GroupRolesUpdateGroupsGroupIdRolesRoleIdPatchErrors]

export type GroupRolesUpdateGroupsGroupIdRolesRoleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsSemesterTransferGroupsGroupIdSemesterTransferGetData = {
    body?: never
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: {
        /**
         * Source Semester
         */
        source_semester?: number | null
        /**
         * Target Semester
         */
        target_semester?: number | null
    }
    url: "/groups/{group_id}/semester-transfer"
}

export type GroupsSemesterTransferGroupsGroupIdSemesterTransferGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsSemesterTransferGroupsGroupIdSemesterTransferGetError =
    GroupsSemesterTransferGroupsGroupIdSemesterTransferGetErrors[keyof GroupsSemesterTransferGroupsGroupIdSemesterTransferGetErrors]

export type GroupsSemesterTransferGroupsGroupIdSemesterTransferGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsApplySemesterTransferGroupsGroupIdSemesterTransferPostData = {
    body: BodyGroupsApplySemesterTransferGroupsGroupIdSemesterTransferPost
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}/semester-transfer"
}

export type GroupsApplySemesterTransferGroupsGroupIdSemesterTransferPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsApplySemesterTransferGroupsGroupIdSemesterTransferPostError =
    GroupsApplySemesterTransferGroupsGroupIdSemesterTransferPostErrors[keyof GroupsApplySemesterTransferGroupsGroupIdSemesterTransferPostErrors]

export type GroupsApplySemesterTransferGroupsGroupIdSemesterTransferPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GroupsDetailStatsGroupsGroupIdStatsGetData = {
    body?: never
    path: {
        /**
         * Group Id
         */
        group_id: number
    }
    query?: never
    url: "/groups/{group_id}/stats"
}

export type GroupsDetailStatsGroupsGroupIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GroupsDetailStatsGroupsGroupIdStatsGetError =
    GroupsDetailStatsGroupsGroupIdStatsGetErrors[keyof GroupsDetailStatsGroupsGroupIdStatsGetErrors]

export type GroupsDetailStatsGroupsGroupIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GetHealthData = {
    body?: never
    path?: never
    query?: never
    url: "/health"
}

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse
}

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses]

export type GetAuthenticatedPhotoImagesVolunteerIdGetData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: {
        /**
         * Size
         */
        size?: number | null
    }
    url: "/images/{volunteer_id}"
}

export type GetAuthenticatedPhotoImagesVolunteerIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetAuthenticatedPhotoImagesVolunteerIdGetError =
    GetAuthenticatedPhotoImagesVolunteerIdGetErrors[keyof GetAuthenticatedPhotoImagesVolunteerIdGetErrors]

export type GetAuthenticatedPhotoImagesVolunteerIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type StopImpersonationImpersonationStopPostData = {
    body?: never
    path?: never
    query?: never
    url: "/impersonation/stop"
}

export type StopImpersonationImpersonationStopPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type LoginPageLoginGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Message
         */
        message?: string | null
    }
    url: "/login"
}

export type LoginPageLoginGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type LoginPageLoginGetError = LoginPageLoginGetErrors[keyof LoginPageLoginGetErrors]

export type LoginPageLoginGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type LoginSubmitLoginPostData = {
    body: BodyLoginSubmitLoginPost
    path?: never
    query?: never
    url: "/login"
}

export type LoginSubmitLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type LoginSubmitLoginPostError = LoginSubmitLoginPostErrors[keyof LoginSubmitLoginPostErrors]

export type LoginSubmitLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type LogoutLogoutPostData = {
    body?: never
    path?: never
    query?: never
    url: "/logout"
}

export type LogoutLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GetDocumentMediaDocumentsDocumentPathGetData = {
    body?: never
    path: {
        /**
         * Document Path
         */
        document_path: string
    }
    query: {
        /**
         * Token
         */
        token: string
    }
    url: "/media/documents/{document_path}"
}

export type GetDocumentMediaDocumentsDocumentPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetDocumentMediaDocumentsDocumentPathGetError =
    GetDocumentMediaDocumentsDocumentPathGetErrors[keyof GetDocumentMediaDocumentsDocumentPathGetErrors]

export type GetDocumentMediaDocumentsDocumentPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type GetPhotoMediaPhotosPhotoPathGetData = {
    body?: never
    path: {
        /**
         * Photo Path
         */
        photo_path: string
    }
    query: {
        /**
         * Token
         */
        token: string
        /**
         * Size
         */
        size?: number | null
    }
    url: "/media/photos/{photo_path}"
}

export type GetPhotoMediaPhotosPhotoPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetPhotoMediaPhotosPhotoPathGetError =
    GetPhotoMediaPhotosPhotoPathGetErrors[keyof GetPhotoMediaPhotosPhotoPathGetErrors]

export type GetPhotoMediaPhotosPhotoPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type MobileCardAprilStateUpdateMobileCardAprilStatePostData = {
    body: BodyMobileCardAprilStateUpdateMobileCardAprilStatePost
    path?: never
    query?: never
    url: "/mobile-card-april-state"
}

export type MobileCardAprilStateUpdateMobileCardAprilStatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type MobileCardAprilStateUpdateMobileCardAprilStatePostError =
    MobileCardAprilStateUpdateMobileCardAprilStatePostErrors[keyof MobileCardAprilStateUpdateMobileCardAprilStatePostErrors]

export type MobileCardAprilStateUpdateMobileCardAprilStatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type MyAccountDetailMyAccountGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Password Error
         */
        password_error?: string | null
        /**
         * Password Message
         */
        password_message?: string | null
    }
    url: "/my-account"
}

export type MyAccountDetailMyAccountGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type MyAccountDetailMyAccountGetError =
    MyAccountDetailMyAccountGetErrors[keyof MyAccountDetailMyAccountGetErrors]

export type MyAccountDetailMyAccountGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type MyAccountUpdateMyAccountPatchData = {
    body: BodyMyAccountUpdateMyAccountPatch
    path?: never
    query?: never
    url: "/my-account"
}

export type MyAccountUpdateMyAccountPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type MyAccountUpdateMyAccountPatchError =
    MyAccountUpdateMyAccountPatchErrors[keyof MyAccountUpdateMyAccountPatchErrors]

export type MyAccountUpdateMyAccountPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type MyAccountChangePasswordMyAccountPasswordPostData = {
    body: BodyMyAccountChangePasswordMyAccountPasswordPost
    path?: never
    query?: never
    url: "/my-account/password"
}

export type MyAccountChangePasswordMyAccountPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type MyAccountChangePasswordMyAccountPasswordPostError =
    MyAccountChangePasswordMyAccountPasswordPostErrors[keyof MyAccountChangePasswordMyAccountPasswordPostErrors]

export type MyAccountChangePasswordMyAccountPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type SetPasswordPageSetPasswordGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Error
         */
        error?: string | null
    }
    url: "/set-password"
}

export type SetPasswordPageSetPasswordGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type SetPasswordPageSetPasswordGetError =
    SetPasswordPageSetPasswordGetErrors[keyof SetPasswordPageSetPasswordGetErrors]

export type SetPasswordPageSetPasswordGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type SetPasswordSubmitSetPasswordPostData = {
    body: BodySetPasswordSubmitSetPasswordPost
    path?: never
    query?: never
    url: "/set-password"
}

export type SetPasswordSubmitSetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type SetPasswordSubmitSetPasswordPostError =
    SetPasswordSubmitSetPasswordPostErrors[keyof SetPasswordSubmitSetPasswordPostErrors]

export type SetPasswordSubmitSetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type SpotifyCallbackSpotifyCallbackGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Code
         */
        code?: string | null
        /**
         * State
         */
        state?: string | null
        /**
         * Error
         */
        error?: string | null
    }
    url: "/spotify/callback"
}

export type SpotifyCallbackSpotifyCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type SpotifyCallbackSpotifyCallbackGetError =
    SpotifyCallbackSpotifyCallbackGetErrors[keyof SpotifyCallbackSpotifyCallbackGetErrors]

export type SpotifyCallbackSpotifyCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type SpotifyLoginSpotifyLoginGetData = {
    body?: never
    path?: never
    query?: never
    url: "/spotify/login"
}

export type SpotifyLoginSpotifyLoginGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type SpotifyLogoutSpotifyLogoutPostData = {
    body?: never
    path?: never
    query?: never
    url: "/spotify/logout"
}

export type SpotifyLogoutSpotifyLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type SpotifyNowPlayingPageSpotifyNowPlayingGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Message
         */
        message?: string | null
        /**
         * Error
         */
        error?: string | null
    }
    url: "/spotify/now-playing"
}

export type SpotifyNowPlayingPageSpotifyNowPlayingGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type SpotifyNowPlayingPageSpotifyNowPlayingGetError =
    SpotifyNowPlayingPageSpotifyNowPlayingGetErrors[keyof SpotifyNowPlayingPageSpotifyNowPlayingGetErrors]

export type SpotifyNowPlayingPageSpotifyNowPlayingGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationsIndexVolunteerApplicationsGetData = {
    body?: never
    path?: never
    query?: never
    url: "/volunteer-applications"
}

export type VolunteerApplicationsIndexVolunteerApplicationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationsCreateInviteVolunteerApplicationsPostData = {
    body: BodyVolunteerApplicationsCreateInviteVolunteerApplicationsPost
    path?: never
    query?: never
    url: "/volunteer-applications"
}

export type VolunteerApplicationsCreateInviteVolunteerApplicationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationsCreateInviteVolunteerApplicationsPostError =
    VolunteerApplicationsCreateInviteVolunteerApplicationsPostErrors[keyof VolunteerApplicationsCreateInviteVolunteerApplicationsPostErrors]

export type VolunteerApplicationsCreateInviteVolunteerApplicationsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationAssignmentFieldsVolunteerApplicationsAssignmentFieldsGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Group Id
         */
        group_id?: number | null
    }
    url: "/volunteer-applications/assignment-fields"
}

export type VolunteerApplicationAssignmentFieldsVolunteerApplicationsAssignmentFieldsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationAssignmentFieldsVolunteerApplicationsAssignmentFieldsGetError =
    VolunteerApplicationAssignmentFieldsVolunteerApplicationsAssignmentFieldsGetErrors[keyof VolunteerApplicationAssignmentFieldsVolunteerApplicationsAssignmentFieldsGetErrors]

export type VolunteerApplicationAssignmentFieldsVolunteerApplicationsAssignmentFieldsGetResponses =
    {
        /**
         * Successful Response
         */
        200: unknown
    }

export type VolunteerRecentRegistrationsVolunteerApplicationsRecentRegistrationsGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null
    }
    url: "/volunteer-applications/recent-registrations"
}

export type VolunteerRecentRegistrationsVolunteerApplicationsRecentRegistrationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerRecentRegistrationsVolunteerApplicationsRecentRegistrationsGetError =
    VolunteerRecentRegistrationsVolunteerApplicationsRecentRegistrationsGetErrors[keyof VolunteerRecentRegistrationsVolunteerApplicationsRecentRegistrationsGetErrors]

export type VolunteerRecentRegistrationsVolunteerApplicationsRecentRegistrationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationDeleteVolunteerApplicationsApplicationIdDeleteData = {
    body?: never
    path: {
        /**
         * Application Id
         */
        application_id: number
    }
    query?: never
    url: "/volunteer-applications/{application_id}"
}

export type VolunteerApplicationDeleteVolunteerApplicationsApplicationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationDeleteVolunteerApplicationsApplicationIdDeleteError =
    VolunteerApplicationDeleteVolunteerApplicationsApplicationIdDeleteErrors[keyof VolunteerApplicationDeleteVolunteerApplicationsApplicationIdDeleteErrors]

export type VolunteerApplicationDeleteVolunteerApplicationsApplicationIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationDetailVolunteerApplicationsApplicationIdGetData = {
    body?: never
    path: {
        /**
         * Application Id
         */
        application_id: number
    }
    query?: never
    url: "/volunteer-applications/{application_id}"
}

export type VolunteerApplicationDetailVolunteerApplicationsApplicationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationDetailVolunteerApplicationsApplicationIdGetError =
    VolunteerApplicationDetailVolunteerApplicationsApplicationIdGetErrors[keyof VolunteerApplicationDetailVolunteerApplicationsApplicationIdGetErrors]

export type VolunteerApplicationDetailVolunteerApplicationsApplicationIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationApproveVolunteerApplicationsApplicationIdApprovalPostData = {
    body?: BodyVolunteerApplicationApproveVolunteerApplicationsApplicationIdApprovalPost
    path: {
        /**
         * Application Id
         */
        application_id: number
    }
    query?: never
    url: "/volunteer-applications/{application_id}/approval"
}

export type VolunteerApplicationApproveVolunteerApplicationsApplicationIdApprovalPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationApproveVolunteerApplicationsApplicationIdApprovalPostError =
    VolunteerApplicationApproveVolunteerApplicationsApplicationIdApprovalPostErrors[keyof VolunteerApplicationApproveVolunteerApplicationsApplicationIdApprovalPostErrors]

export type VolunteerApplicationApproveVolunteerApplicationsApplicationIdApprovalPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationResendVolunteerApplicationsApplicationIdResendPostData = {
    body?: never
    path: {
        /**
         * Application Id
         */
        application_id: number
    }
    query?: never
    url: "/volunteer-applications/{application_id}/resend"
}

export type VolunteerApplicationResendVolunteerApplicationsApplicationIdResendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerApplicationResendVolunteerApplicationsApplicationIdResendPostError =
    VolunteerApplicationResendVolunteerApplicationsApplicationIdResendPostErrors[keyof VolunteerApplicationResendVolunteerApplicationsApplicationIdResendPostErrors]

export type VolunteerApplicationResendVolunteerApplicationsApplicationIdResendPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerApplicationMarkTrialAttendanceVolunteerApplicationsApplicationIdTrialAttendancePostData =
    {
        body: BodyVolunteerApplicationMarkTrialAttendanceVolunteerApplicationsApplicationIdTrialAttendancePost
        path: {
            /**
             * Application Id
             */
            application_id: number
        }
        query?: never
        url: "/volunteer-applications/{application_id}/trial-attendance"
    }

export type VolunteerApplicationMarkTrialAttendanceVolunteerApplicationsApplicationIdTrialAttendancePostErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError
    }

export type VolunteerApplicationMarkTrialAttendanceVolunteerApplicationsApplicationIdTrialAttendancePostError =
    VolunteerApplicationMarkTrialAttendanceVolunteerApplicationsApplicationIdTrialAttendancePostErrors[keyof VolunteerApplicationMarkTrialAttendanceVolunteerApplicationsApplicationIdTrialAttendancePostErrors]

export type VolunteerApplicationMarkTrialAttendanceVolunteerApplicationsApplicationIdTrialAttendancePostResponses =
    {
        /**
         * Successful Response
         */
        200: unknown
    }

export type VolunteersIndexVolunteersGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Q
         */
        q?: string | null
        /**
         * Cursor
         */
        cursor?: string | null
        /**
         * Only Active
         */
        only_active?: string | null
    }
    url: "/volunteers"
}

export type VolunteersIndexVolunteersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteersIndexVolunteersGetError =
    VolunteersIndexVolunteersGetErrors[keyof VolunteersIndexVolunteersGetErrors]

export type VolunteersIndexVolunteersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteersResultsVolunteersListGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Q
         */
        q?: string | null
        /**
         * Cursor
         */
        cursor?: string | null
        /**
         * Only Active
         */
        only_active?: string | null
    }
    url: "/volunteers/list"
}

export type VolunteersResultsVolunteersListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteersResultsVolunteersListGetError =
    VolunteersResultsVolunteersListGetErrors[keyof VolunteersResultsVolunteersListGetErrors]

export type VolunteersResultsVolunteersListGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type SearchVolunteersPageVolunteersSearchGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Birth Date After
         */
        birth_date_after?: string | null
        /**
         * Birth Date Before
         */
        birth_date_before?: string | null
        /**
         * Pingvin Points Above
         */
        pingvin_points_above?: string | null
        /**
         * Pingvin Points Below
         */
        pingvin_points_below?: string | null
        /**
         * Has Active Signed Contract
         */
        has_active_signed_contract?: string | null
        /**
         * Include Groups
         */
        include_groups?: Array<number>
        /**
         * Include Current Groups
         */
        include_current_groups?: Array<number>
        /**
         * Exclude Groups
         */
        exclude_groups?: Array<number>
        /**
         * Exclude Current Groups
         */
        exclude_current_groups?: Array<number>
        /**
         * Include Courses
         */
        include_courses?: Array<number>
        /**
         * Exclude Courses
         */
        exclude_courses?: Array<number>
    }
    url: "/volunteers/search"
}

export type SearchVolunteersPageVolunteersSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type SearchVolunteersPageVolunteersSearchGetError =
    SearchVolunteersPageVolunteersSearchGetErrors[keyof SearchVolunteersPageVolunteersSearchGetErrors]

export type SearchVolunteersPageVolunteersSearchGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerSearchCourseOptionsVolunteersSearchOptionsCoursesGetData = {
    body?: never
    path?: never
    query: {
        /**
         * Field
         */
        field: string
        /**
         * Selected
         */
        selected?: string | null
    }
    url: "/volunteers/search/options/courses"
}

export type VolunteerSearchCourseOptionsVolunteersSearchOptionsCoursesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerSearchCourseOptionsVolunteersSearchOptionsCoursesGetError =
    VolunteerSearchCourseOptionsVolunteersSearchOptionsCoursesGetErrors[keyof VolunteerSearchCourseOptionsVolunteersSearchOptionsCoursesGetErrors]

export type VolunteerSearchCourseOptionsVolunteersSearchOptionsCoursesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerSearchGroupOptionsVolunteersSearchOptionsGroupsGetData = {
    body?: never
    path?: never
    query: {
        /**
         * Field
         */
        field: string
        /**
         * Selected
         */
        selected?: string | null
    }
    url: "/volunteers/search/options/groups"
}

export type VolunteerSearchGroupOptionsVolunteersSearchOptionsGroupsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerSearchGroupOptionsVolunteersSearchOptionsGroupsGetError =
    VolunteerSearchGroupOptionsVolunteersSearchOptionsGroupsGetErrors[keyof VolunteerSearchGroupOptionsVolunteersSearchOptionsGroupsGetErrors]

export type VolunteerSearchGroupOptionsVolunteersSearchOptionsGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerSearchTypeaheadOptionsVolunteersSearchOptionsTypeaheadGetData = {
    body?: never
    path?: never
    query?: {
        /**
         * Q
         */
        q?: string | null
    }
    url: "/volunteers/search/options/typeahead"
}

export type VolunteerSearchTypeaheadOptionsVolunteersSearchOptionsTypeaheadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerSearchTypeaheadOptionsVolunteersSearchOptionsTypeaheadGetError =
    VolunteerSearchTypeaheadOptionsVolunteersSearchOptionsTypeaheadGetErrors[keyof VolunteerSearchTypeaheadOptionsVolunteersSearchOptionsTypeaheadGetErrors]

export type VolunteerSearchTypeaheadOptionsVolunteersSearchOptionsTypeaheadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteersStatsVolunteersStatsGetData = {
    body?: never
    path?: never
    query?: never
    url: "/volunteers/stats"
}

export type VolunteersStatsVolunteersStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerDeleteVolunteersVolunteerIdDeleteData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}"
}

export type VolunteerDeleteVolunteersVolunteerIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerDeleteVolunteersVolunteerIdDeleteError =
    VolunteerDeleteVolunteersVolunteerIdDeleteErrors[keyof VolunteerDeleteVolunteersVolunteerIdDeleteErrors]

export type VolunteerDeleteVolunteersVolunteerIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerDetailVolunteersVolunteerIdGetData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}"
}

export type VolunteerDetailVolunteersVolunteerIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerDetailVolunteersVolunteerIdGetError =
    VolunteerDetailVolunteersVolunteerIdGetErrors[keyof VolunteerDetailVolunteersVolunteerIdGetErrors]

export type VolunteerDetailVolunteersVolunteerIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerUpdateProfileVolunteersVolunteerIdPatchData = {
    body: BodyVolunteerUpdateProfileVolunteersVolunteerIdPatch
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}"
}

export type VolunteerUpdateProfileVolunteersVolunteerIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerUpdateProfileVolunteersVolunteerIdPatchError =
    VolunteerUpdateProfileVolunteersVolunteerIdPatchErrors[keyof VolunteerUpdateProfileVolunteersVolunteerIdPatchErrors]

export type VolunteerUpdateProfileVolunteersVolunteerIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerAddCourseCompletionVolunteersVolunteerIdCourseCompletionsPostData = {
    body: BodyVolunteerAddCourseCompletionVolunteersVolunteerIdCourseCompletionsPost
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}/course-completions"
}

export type VolunteerAddCourseCompletionVolunteersVolunteerIdCourseCompletionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerAddCourseCompletionVolunteersVolunteerIdCourseCompletionsPostError =
    VolunteerAddCourseCompletionVolunteersVolunteerIdCourseCompletionsPostErrors[keyof VolunteerAddCourseCompletionVolunteersVolunteerIdCourseCompletionsPostErrors]

export type VolunteerAddCourseCompletionVolunteersVolunteerIdCourseCompletionsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerCourseCompletionsPanelVolunteersVolunteerIdCourseCompletionsPanelGetData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}/course-completions/panel"
}

export type VolunteerCourseCompletionsPanelVolunteersVolunteerIdCourseCompletionsPanelGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerCourseCompletionsPanelVolunteersVolunteerIdCourseCompletionsPanelGetError =
    VolunteerCourseCompletionsPanelVolunteersVolunteerIdCourseCompletionsPanelGetErrors[keyof VolunteerCourseCompletionsPanelVolunteersVolunteerIdCourseCompletionsPanelGetErrors]

export type VolunteerCourseCompletionsPanelVolunteersVolunteerIdCourseCompletionsPanelGetResponses =
    {
        /**
         * Successful Response
         */
        200: unknown
    }

export type VolunteerDeleteCourseCompletionVolunteersVolunteerIdCourseCompletionsCompletionIdDeleteData =
    {
        body?: never
        path: {
            /**
             * Volunteer Id
             */
            volunteer_id: number
            /**
             * Completion Id
             */
            completion_id: number
        }
        query?: never
        url: "/volunteers/{volunteer_id}/course-completions/{completion_id}"
    }

export type VolunteerDeleteCourseCompletionVolunteersVolunteerIdCourseCompletionsCompletionIdDeleteErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError
    }

export type VolunteerDeleteCourseCompletionVolunteersVolunteerIdCourseCompletionsCompletionIdDeleteError =
    VolunteerDeleteCourseCompletionVolunteersVolunteerIdCourseCompletionsCompletionIdDeleteErrors[keyof VolunteerDeleteCourseCompletionVolunteersVolunteerIdCourseCompletionsCompletionIdDeleteErrors]

export type VolunteerDeleteCourseCompletionVolunteersVolunteerIdCourseCompletionsCompletionIdDeleteResponses =
    {
        /**
         * Successful Response
         */
        200: unknown
    }

export type VolunteerDocumentsPanelVolunteersVolunteerIdDocumentsPanelGetData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}/documents/panel"
}

export type VolunteerDocumentsPanelVolunteersVolunteerIdDocumentsPanelGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerDocumentsPanelVolunteersVolunteerIdDocumentsPanelGetError =
    VolunteerDocumentsPanelVolunteersVolunteerIdDocumentsPanelGetErrors[keyof VolunteerDocumentsPanelVolunteersVolunteerIdDocumentsPanelGetErrors]

export type VolunteerDocumentsPanelVolunteersVolunteerIdDocumentsPanelGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerDeleteDocumentVolunteersVolunteerIdDocumentsDocumentIdDeleteData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
        /**
         * Document Id
         */
        document_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}/documents/{document_id}"
}

export type VolunteerDeleteDocumentVolunteersVolunteerIdDocumentsDocumentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerDeleteDocumentVolunteersVolunteerIdDocumentsDocumentIdDeleteError =
    VolunteerDeleteDocumentVolunteersVolunteerIdDocumentsDocumentIdDeleteErrors[keyof VolunteerDeleteDocumentVolunteersVolunteerIdDocumentsDocumentIdDeleteErrors]

export type VolunteerDeleteDocumentVolunteersVolunteerIdDocumentsDocumentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerDeletePhotoVolunteersVolunteerIdPhotoDeleteData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}/photo"
}

export type VolunteerDeletePhotoVolunteersVolunteerIdPhotoDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerDeletePhotoVolunteersVolunteerIdPhotoDeleteError =
    VolunteerDeletePhotoVolunteersVolunteerIdPhotoDeleteErrors[keyof VolunteerDeletePhotoVolunteersVolunteerIdPhotoDeleteErrors]

export type VolunteerDeletePhotoVolunteersVolunteerIdPhotoDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerUploadPhotoVolunteersVolunteerIdPhotoPostData = {
    body: BodyVolunteerUploadPhotoVolunteersVolunteerIdPhotoPost
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}/photo"
}

export type VolunteerUploadPhotoVolunteersVolunteerIdPhotoPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerUploadPhotoVolunteersVolunteerIdPhotoPostError =
    VolunteerUploadPhotoVolunteersVolunteerIdPhotoPostErrors[keyof VolunteerUploadPhotoVolunteersVolunteerIdPhotoPostErrors]

export type VolunteerUploadPhotoVolunteersVolunteerIdPhotoPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerUpdateRelationsVolunteersVolunteerIdRelationsPatchData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}/relations"
}

export type VolunteerUpdateRelationsVolunteersVolunteerIdRelationsPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerUpdateRelationsVolunteersVolunteerIdRelationsPatchError =
    VolunteerUpdateRelationsVolunteersVolunteerIdRelationsPatchErrors[keyof VolunteerUpdateRelationsVolunteersVolunteerIdRelationsPatchErrors]

export type VolunteerUpdateRelationsVolunteersVolunteerIdRelationsPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerRelationsPanelVolunteersVolunteerIdRelationsPanelGetData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: {
        /**
         * Edit
         */
        edit?: boolean
    }
    url: "/volunteers/{volunteer_id}/relations/panel"
}

export type VolunteerRelationsPanelVolunteersVolunteerIdRelationsPanelGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerRelationsPanelVolunteersVolunteerIdRelationsPanelGetError =
    VolunteerRelationsPanelVolunteersVolunteerIdRelationsPanelGetErrors[keyof VolunteerRelationsPanelVolunteersVolunteerIdRelationsPanelGetErrors]

export type VolunteerRelationsPanelVolunteersVolunteerIdRelationsPanelGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerAddRoleAssignmentVolunteersVolunteerIdRoleAssignmentsPostData = {
    body: BodyVolunteerAddRoleAssignmentVolunteersVolunteerIdRoleAssignmentsPost
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: never
    url: "/volunteers/{volunteer_id}/role-assignments"
}

export type VolunteerAddRoleAssignmentVolunteersVolunteerIdRoleAssignmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerAddRoleAssignmentVolunteersVolunteerIdRoleAssignmentsPostError =
    VolunteerAddRoleAssignmentVolunteersVolunteerIdRoleAssignmentsPostErrors[keyof VolunteerAddRoleAssignmentVolunteersVolunteerIdRoleAssignmentsPostErrors]

export type VolunteerAddRoleAssignmentVolunteersVolunteerIdRoleAssignmentsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerRoleAssignmentsPanelVolunteersVolunteerIdRoleAssignmentsPanelGetData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: {
        /**
         * Edit Assignment Id
         */
        edit_assignment_id?: number | null
    }
    url: "/volunteers/{volunteer_id}/role-assignments/panel"
}

export type VolunteerRoleAssignmentsPanelVolunteersVolunteerIdRoleAssignmentsPanelGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type VolunteerRoleAssignmentsPanelVolunteersVolunteerIdRoleAssignmentsPanelGetError =
    VolunteerRoleAssignmentsPanelVolunteersVolunteerIdRoleAssignmentsPanelGetErrors[keyof VolunteerRoleAssignmentsPanelVolunteersVolunteerIdRoleAssignmentsPanelGetErrors]

export type VolunteerRoleAssignmentsPanelVolunteersVolunteerIdRoleAssignmentsPanelGetResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VolunteerRoleAssignmentRoleFieldVolunteersVolunteerIdRoleAssignmentsRoleFieldGetData = {
    body?: never
    path: {
        /**
         * Volunteer Id
         */
        volunteer_id: number
    }
    query?: {
        /**
         * Group Id
         */
        group_id?: number | null
        /**
         * Role Id
         */
        role_id?: number | null
        /**
         * Year
         */
        year?: number | null
        /**
         * Term
         */
        term?: number | null
    }
    url: "/volunteers/{volunteer_id}/role-assignments/role-field"
}

export type VolunteerRoleAssignmentRoleFieldVolunteersVolunteerIdRoleAssignmentsRoleFieldGetErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError
    }

export type VolunteerRoleAssignmentRoleFieldVolunteersVolunteerIdRoleAssignmentsRoleFieldGetError =
    VolunteerRoleAssignmentRoleFieldVolunteersVolunteerIdRoleAssignmentsRoleFieldGetErrors[keyof VolunteerRoleAssignmentRoleFieldVolunteersVolunteerIdRoleAssignmentsRoleFieldGetErrors]

export type VolunteerRoleAssignmentRoleFieldVolunteersVolunteerIdRoleAssignmentsRoleFieldGetResponses =
    {
        /**
         * Successful Response
         */
        200: unknown
    }

export type VolunteerDeleteRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdDeleteData =
    {
        body?: never
        path: {
            /**
             * Volunteer Id
             */
            volunteer_id: number
            /**
             * Assignment Id
             */
            assignment_id: number
        }
        query?: never
        url: "/volunteers/{volunteer_id}/role-assignments/{assignment_id}"
    }

export type VolunteerDeleteRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdDeleteErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError
    }

export type VolunteerDeleteRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdDeleteError =
    VolunteerDeleteRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdDeleteErrors[keyof VolunteerDeleteRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdDeleteErrors]

export type VolunteerDeleteRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdDeleteResponses =
    {
        /**
         * Successful Response
         */
        200: unknown
    }

export type VolunteerUpdateRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdPatchData =
    {
        body: BodyVolunteerUpdateRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdPatch
        path: {
            /**
             * Volunteer Id
             */
            volunteer_id: number
            /**
             * Assignment Id
             */
            assignment_id: number
        }
        query?: never
        url: "/volunteers/{volunteer_id}/role-assignments/{assignment_id}"
    }

export type VolunteerUpdateRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdPatchErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError
    }

export type VolunteerUpdateRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdPatchError =
    VolunteerUpdateRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdPatchErrors[keyof VolunteerUpdateRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdPatchErrors]

export type VolunteerUpdateRoleAssignmentVolunteersVolunteerIdRoleAssignmentsAssignmentIdPatchResponses =
    {
        /**
         * Successful Response
         */
        200: unknown
    }
