export type {
    BlifrivilligPageContent,
    EventDetail,
    EventGroup,
    EventRoom,
    EventsPageContent,
    EventType,
    GroupsPageContent,
    HomePageContent,
    NavbarContent,
    NavGroup,
    NavItem,
    NavLeaf,
    PageContent,
    PublishedEvent,
    RoomDetail,
    RoomSummary,
    RoomsPageContent,
    SiteMetadataContent,
    SourcedImage,
    SponsorsPageContent,
    StudentGroupDetail,
    StudentGroupSummary,
} from "./fetch"
export type {
    Arrangement,
    BlifrivilligPage,
    EventsPage,
    Footer,
    GroupsPage,
    HomePage,
    KontaktPage,
    LinkInBio,
    Navbar,
    Page,
    Room,
    RoomsPage,
    SiteMetadata,
    SponsorsPage,
    StudentGroup,
} from "./sanity.types"
